version: '3'

services:
  web:
    build: .
    restart: always
    container_name: flask_container
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgresql
      DB_NAME: postgres
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data 777

